# Site settings
title: "Shabda Raaj: Developer and Salesman"
email: shabda@agiliq.com
description: ""
baseurl: ""
url: "http://shabdaraaj.com"

# Build settings
markdown: kramdown
permalink: /writings/:categories/:title.html
